version: 2

run:
  timeout: 5m
  tests: true
  fix: true                     # 能自动修的尽量自动修（gofumpt/goimports 等）
  modules-download-mode: mod
  allow-parallel-runners: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.gen\\.go$"
    - ".*_mock\\.go$"
    - "^zz_.*\\.go$"
    - ".*\\.pb\\.go$"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: HEAD           # 只看相对当前分支新增问题时很有用（本地/CI 可酌情保留）
  exclude-rules:
    # 测试里放宽圈复杂度/重复代码
    - path: _test\\.go
      linters:
        - gocyclo
    # 允许在测试里出现未检查的错误（比如辅助断言场景），可按需删除
    - path: _test\\.go
      linters:
        - errcheck
    # 允许生成文件跳过大部分风格类检查（保险起见）
    - path: ".*(\\.gen\\.go|_mock\\.go|\\.pb\\.go)$"
      linters:
        - revive
        - gocyclo
        - dupl
        - goconst

linters:
  disable-all: true
  enable:
    # 语义与静态分析
    - govet
    - staticcheck
    - unused
    - errcheck
    - errorlint
    - ineffassign
    - unconvert
    - prealloc
    - goconst
    - gocyclo
    - dupl
    - misspell
    # 代码风格/格式（使用 formatter 配置）
    - revive
    - nolintlint            # 约束 //nolint 的使用，避免滥用
    # 额外实用
    - durationcheck         # 时间单位误用检查
    - copyloopvar           # 循环变量捕获（Go1.22+ 仍有场景可报）
    # 可选安全（如需安全扫描可开启）
    # - gosec

formatters:
  enable:
    - gofumpt               # 用 gofumpt 取代 gofmt（更严格）
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 12        # 略放宽到 12，减少误报；核心热点再局部优化
  misspell:
    locale: US
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: exported
      - name: if-return
      - name: early-return
      - name: unnecessary-stmt
      - name: empty-lines
      - name: indent-error-flow
      - name: blank-imports
      - name: import-shadowing
      - name: range-val-in-closure
      - name: receiver-naming
      - name: time-naming
      - name: error-naming
      - name: error-strings
      - name: errorf
      - name: unexported-return
        disabled: true
  goconst:
    min-len: 2
    min-occurrences: 3
  dupl:
    threshold: 120            # 合理阈值，避免对测试/样板过度敏感
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true # 要求 //nolint 必须附解释
    require-specific: true    # 要求指明具体 linter 名称
  govet:
    check-shadowing: true
    enable:
      - atomicalign
      - bools
      - copylocks
      - fieldalignment
      - printf
      - shadow
      - sortslice
      - unreachable
      - unusedresult
      - nilness

formatter-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/NSObjects/go-template

# 可在不同 CI 场景下使用的构建标签
# build-tags:
#   - integration
#   - e2e
