services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-template-api
    volumes:
      - ./configs/config.toml:/configs/config.toml
    ports:
      - "9322:9322"
    networks:
      - api-net
networks:
  api-net:
    driver: bridge
