// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Username  string    `gorm:"column:username;type:varchar(50);index:username_idx,priority:1" json:"username"`
	Email     string    `gorm:"column:email;type:varchar(100);index:email_idx,priority:1" json:"email"`
	Mobile    string    `gorm:"column:mobile;type:varchar(20)" json:"mobile"`
	Password  string    `gorm:"column:password;type:char(60)" json:"password"`
	Gender    int32     `gorm:"column:gender;type:tinyint" json:"gender"`
	Age       int32     `gorm:"column:age;type:tinyint unsigned" json:"age"`
	Status    int32     `gorm:"column:status;type:tinyint;default:1" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;index:created_at_idx,priority:1;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP" json:"updated_at"`
	LastLogin time.Time `gorm:"column:last_login;type:datetime" json:"last_login"`
	Bio       string    `gorm:"column:bio;type:text" json:"bio"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
